# Generated by Django 5.2 on 2026-07-24 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_jobseeker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='contectno',
            new_name='contactno',
        ),
        migrations.RenameField(
            model_name='jobseeker',
            old_name='exprience',
            new_name='experience',
        ),
    ]
