# Generated by Django 5.2 on 2026-07-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_contectno_jobseeker_contactno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=12)),
                ('emailaddress', models.EmailField(max_length=50)),
                ('Enquirytext', models.TextField()),
                ('posteddade', models.CharField(max_length=30)),
            ],
        ),
    ]
